sudo: required

services:
  - docker

before_install:
  - docker build -t backend -f Dockerfile.dev .

script:
  - docker run backend npm run test -- --coverage


deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "backend"
  env: Backend-env

  bucket_name: "elasticbeanstalk-us-east-2-926812029837"
  bucket_path: "backend"
  on:
    branch: master

  access_key_id: $aws_acc
  secret_access_key:
    secure: "$aws_sec"
